# the compiler to use
CC = clang

CFLAGS = -march=native -mtune=native -msse4.2 -std=c++14 -Ofast

LFLAGS =  -lboost_system
IFLAGS = -Iinclude

TARGET = InputParserTest

all: $(TARGET)
$(TARGET): $(TARGET).cpp; $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp $(LFLAGS) $(IFLAGS)